# Generated by Django 3.2.7 on 2021-11-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centerhead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=120)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('admitted', 'admitted'), ('not-intrested', 'not-intrested'), ('followup', 'followup')], default='followup', max_length=50)),
                ('followup_date', models.DateField(null=True)),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centerhead.course')),
            ],
        ),
    ]
